### ISSUE TITLE
Add support for events

### ISSUE THREAD

**Issue by gelvetica** [gelvetica/televisionapplication#1]
notes:

- event pages use /event instead of /tv -- `Tokensniffer.refresh()` has /tv hardcoded, needs to be changed
- all future events are visible on the homepage, can be parsed using a similar config thats currently used to parse the available channels
- epg is really needed here, not difficult to implement and available for every channel
- epg could be refreshed every 12 hours, homepage should be refreshed each hour to check for new events, as they are often added late
- config needs to be improved to allow users to filter out what type of events they want to appear in the playlist/epg
- there needs to be an endpoint to force refresh the homepage

**Comment by johnhere3000** [comment]
hii brother, can you send me your discord username, want to buy some scraper from u.
thanks
